"""Add Casbin RBAC models

Revision ID: 3b7743dd817a
Revises: aacc90fb11ce
Create Date: 2026-02-23 11:09:02.925051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b7743dd817a'
down_revision: Union[str, Sequence[str], None] = 'aacc90fb11ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbin_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('v0', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v1', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v2', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v3', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v4', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v5', sqlmodel.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casbin_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_casbin_rule_ptype'), ['ptype'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v0'), ['v0'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v1'), ['v1'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v2'), ['v2'], unique=False)

    op.create_table('permission',
    sa.Column('resource', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('action', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_permission_resource'), ['resource'], unique=False)

    op.create_table('role',
    sa.Column('name', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('rolepermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rolepermission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rolepermission_permission_id'), ['permission_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rolepermission_role_id'), ['role_id'], unique=False)

    op.create_table('userrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userrole_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_userrole_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userrole_user_id'))
        batch_op.drop_index(batch_op.f('ix_userrole_role_id'))

    op.drop_table('userrole')
    with op.batch_alter_table('rolepermission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rolepermission_role_id'))
        batch_op.drop_index(batch_op.f('ix_rolepermission_permission_id'))

    op.drop_table('rolepermission')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_resource'))
        batch_op.drop_index(batch_op.f('ix_permission_action'))

    op.drop_table('permission')
    with op.batch_alter_table('casbin_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v2'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v1'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v0'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_ptype'))

    op.drop_table('casbin_rule')
    # ### end Alembic commands ###
