"""add_used_token_table

Revision ID: aacc90fb11ce
Revises: e1ecd002528b
Create Date: 2026-02-22 18:31:14.636227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aacc90fb11ce'
down_revision: Union[str, Sequence[str], None] = 'e1ecd002528b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usedtoken',
    sa.Column('token_jti', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('token_purpose', sqlmodel.AutoString(length=50), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usedtoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usedtoken_token_jti'), ['token_jti'], unique=True)

    with op.batch_alter_table('ipaccesscontrol', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'WHITELISTED', 'BLACKLISTED', name='ipaccessstatus'),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.alter_column('token_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACCESS', 'REFRESH', 'PASSWORD_RESET', 'EMAIL_VERIFICATION', 'TEMP_AUTH', 'BEARER', 'IP_WHITELIST', 'IP_BLACKLIST', name='tokentype'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.alter_column('token_type',
               existing_type=sa.Enum('ACCESS', 'REFRESH', 'PASSWORD_RESET', 'EMAIL_VERIFICATION', 'TEMP_AUTH', 'BEARER', 'IP_WHITELIST', 'IP_BLACKLIST', name='tokentype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('ipaccesscontrol', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('PENDING', 'WHITELISTED', 'BLACKLISTED', name='ipaccessstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('usedtoken', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usedtoken_token_jti'))

    op.drop_table('usedtoken')
    # ### end Alembic commands ###
