"""Add token tracking and IP access control tables

Revision ID: e1ecd002528b
Revises: 6c2aec86ee51
Create Date: 2026-02-22 17:53:55.372944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e1ecd002528b'
down_revision: Union[str, Sequence[str], None] = '6c2aec86ee51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipaccesscontrol',
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=False),
    sa.Column('status', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ipaccesscontrol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ipaccesscontrol_ip_address'), ['ip_address'], unique=False)

    op.create_table('loginattempt',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=False),
    sa.Column('user_agent', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tokentracking',
    sa.Column('token_jti', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('token_type', sqlmodel.AutoString(length=20), nullable=False),
    sa.Column('ip_address', sqlmodel.AutoString(length=45), nullable=False),
    sa.Column('user_agent', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokentracking_token_jti'), ['token_jti'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokentracking_token_jti'))

    op.drop_table('tokentracking')
    op.drop_table('loginattempt')
    with op.batch_alter_table('ipaccesscontrol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ipaccesscontrol_ip_address'))

    op.drop_table('ipaccesscontrol')
    # ### end Alembic commands ###
