"""add_social_login_fields

Revision ID: eec72f00ab92
Revises: 3b7743dd817a
Create Date: 2026-02-24 18:44:56.755577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eec72f00ab92'
down_revision: Union[str, Sequence[str], None] = '3b7743dd817a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casbinrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ptype', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('v0', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v1', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v2', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v3', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v4', sqlmodel.AutoString(length=255), nullable=True),
    sa.Column('v5', sqlmodel.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casbinrule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_casbinrule_ptype'), ['ptype'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbinrule_v0'), ['v0'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbinrule_v1'), ['v1'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbinrule_v2'), ['v2'], unique=False)

    op.create_table('tenant',
    sa.Column('name', sqlmodel.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.AutoString(length=63), nullable=False),
    sa.Column('description', sqlmodel.AutoString(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_slug'), ['slug'], unique=True)

    op.create_table('tenantinvitation',
    sa.Column('email', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='tenantrole'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED', name='invitationstatus'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('invited_by', sa.Integer(), nullable=True),
    sa.Column('token', sqlmodel.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenantinvitation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenantinvitation_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenantinvitation_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenantinvitation_token'), ['token'], unique=True)

    op.create_table('tenantmember',
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='tenantrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenantmember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenantmember_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenantmember_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('casbin_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casbin_rule_ptype'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v0'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v1'))
        batch_op.drop_index(batch_op.f('ix_casbin_rule_v2'))

    op.drop_table('casbin_rule')
    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.alter_column('token_type',
               existing_type=sa.VARCHAR(length=18),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_provider', sqlmodel.AutoString(length=50), nullable=True))
        batch_op.add_column(sa.Column('social_id', sqlmodel.AutoString(length=255), nullable=True))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_user_social_id'), ['social_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_social_provider'), ['social_provider'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_social_provider'))
        batch_op.drop_index(batch_op.f('ix_user_social_id'))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('social_id')
        batch_op.drop_column('social_provider')

    with op.batch_alter_table('tokentracking', schema=None) as batch_op:
        batch_op.alter_column('token_type',
               existing_type=sa.VARCHAR(length=18),
               nullable=False)

    op.create_table('casbin_rule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ptype', sa.VARCHAR(length=255), nullable=False),
    sa.Column('v0', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v2', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v3', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('v5', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('casbin_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_casbin_rule_v2'), ['v2'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v1'), ['v1'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_v0'), ['v0'], unique=False)
        batch_op.create_index(batch_op.f('ix_casbin_rule_ptype'), ['ptype'], unique=False)

    with op.batch_alter_table('tenantmember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenantmember_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenantmember_tenant_id'))

    op.drop_table('tenantmember')
    with op.batch_alter_table('tenantinvitation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenantinvitation_token'))
        batch_op.drop_index(batch_op.f('ix_tenantinvitation_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenantinvitation_email'))

    op.drop_table('tenantinvitation')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_slug'))

    op.drop_table('tenant')
    with op.batch_alter_table('casbinrule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casbinrule_v2'))
        batch_op.drop_index(batch_op.f('ix_casbinrule_v1'))
        batch_op.drop_index(batch_op.f('ix_casbinrule_v0'))
        batch_op.drop_index(batch_op.f('ix_casbinrule_ptype'))

    op.drop_table('casbinrule')
    # ### end Alembic commands ###
